// Dil sozlugu - SAF VERI (JSX yok): hem uygulama hem denetim betigi buradan okur.
// Yeni metin eklerken IKI dile birden ekle; kural: CLAUDE.md madde 1.
export const METINLER = {
  en: {
    locale: "en-US",
    belgeBasligi: "Latent — AI-made films & series",
    nav: {
      kesfet: "Discover",
      yarisma: "Contest",
      yukle: "Upload",
      studyo: "Studio",
      panel: "Review",
      analiz: "Analytics",
    },
    genel: {
      girisYap: "Sign in",
      cikis: "Sign out",
      yukleniyor: "Loading…",
      geri: "← Back",
      film: "Film",
      dizi: "Series",
      FILM: "FILM",
      DIZI: "SERIES",
      seb: (sezon, bolum) => `S${sezon}·E${bolum}`,
      bolumNo: (n) => `Episode ${n}`,
      dil: "Language",
    },
    kabuk: {
      bildirimler: "Notifications",
      bildirimYok: "No notifications yet.",
      yayinda: "is live",
      yeniIcerik: "New title",
      dogrulanmadi: "Your email isn't verified yet — check your inbox.",
      yenidenGonder: "Resend",
      gonderildi: "Link sent ✓",
      altBilgi1: "every title is made entirely with AI.",
      altBilgi2: "Always free to watch · Artists earn per view",
    },
    hataEkrani: {
      baslik: "Something went wrong",
      govde: "An unexpected error occurred. Reloading the page usually fixes it.",
      yenile: "Reload page",
    },
    ayarlar: {
      baslik: "Settings",
      dilBolum: "Language",
      altyaziBolum: "Subtitles",
      altyaziAcik: "Show subtitles automatically",
      altyaziDil: "Subtitle language",
      arayuzDili: "Same as interface",
      kapat: "Done",
      not: "Subtitles appear when the title has a caption track in that language.",
    },
    kesfet: {
      ara: "Search films and series…",
      sonuclar: "Search results",
      sonucYok: "No results found.",
      tumu: "All",
      filmler: "Films",
      diziler: "Series",
      baslikSayisi: (n) => `${n} title${n === 1 ? "" : "s"}`,
      izle: "▶ Watch",
      filmiIzle: "▶ Watch the film",
      devamEt: "Continue watching",
      kaldiginYerden: "pick up where you left off",
      listem: "My list",
      sanaOzel: "For you",
      yeniEklenenler: "New releases",
      diger: "Other",
      listemde: "✓ In my list",
      listemeEkle: "＋ Add to my list",
      paylas: "Share",
      kopyalandi: "Link copied ✓",
      icerikYok: "Nothing is live yet.",
      sunucuYok: "Can't reach the server — check your connection and refresh.",
      katalogHata: (m) => `Couldn't load the catalog: ${m}`,
      baslikHata: (m) => `Couldn't load the title: ${m}`,
    },
    oynatici: {
      sponsorlu: "SPONSORED",
      sponsoruZiyaret: "Visit sponsor",
      baslayacak: (n) => `Video starts in ${n}s…`,
      sonrakiBolum: (n) => `Next episode in ${n}s`,
      simdiOynat: "▶ Play now",
      kal: "Stay",
    },
    giris: {
      girisBaslik: "Sign in",
      kayitBaslik: "Create account",
      girisAlt: "Watching is always free. Sign in to upload and keep lists.",
      kayitAlt: "One account is all it takes to upload as a creator.",
      ad: "Display name",
      eposta: "Email",
      sifre: "Password",
      kayitAlindi: "You're in. Verify your email, then sign in.",
      bekle: "Hold on…",
      kayitOl: "Sign up",
      hesapYok: "No account yet?",
      hesapVar: "Already have an account?",
    },
    profil: {
      baslik: "Profile",
      gorunenAd: "Display name",
      dogrulandi: "Email verified",
      dogrulanmadi: "Email not verified",
      yenidenGonder: "Resend",
      gonderildi: "Sent ✓",
      kaydet: "Save",
      vazgec: "Cancel",
    },
    yukle: {
      baslik: "Upload",
      aciklama:
        "Your video goes straight from the browser to Cloudflare; it goes live after review.",
      baslikEtiket: "Title",
      yeniBaslik: "+ Create a new title",
      ad: "Name",
      tip: "Type",
      tur: "Genre (e.g. Sci-Fi)",
      yil: "Year",
      aciklamaEtiket: "Description",
      sezon: "Season",
      bolum: "Episode",
      bolumAdi: "Episode name",
      dosya: "Video file",
      yukleniyorYuzde: (n) => `Uploading… ${n}%`,
      baslat: "Start upload",
      tamamBaslik: "Upload complete",
      tamamGovde:
        "Your video is processing on Cloudflare. Once ready it enters review; when approved, it goes live.",
      yeniYukleme: "Upload another",
      hataBaslik: (m) => `Couldn't create the title: ${m}`,
      hataUrl: (m) => `Couldn't get an upload URL: ${m}`,
      hataCf: (kod) => `Cloudflare upload error (${kod})`,
      hataAg: "Network error: the upload didn't finish",
    },
    studyo: {
      baslik: "Studio",
      aciklama: "Your titles, their status, and how they're doing.",
      toplamIzlenme: "Total views",
      izlenmeSaati: "Watch hours",
      yayindaBolum: "Episodes live",
      hakedis: "Earnings",
      hakedisAciklama: "Estimated monthly breakdown based on revenue share per view.",
      izlenme: "views",
      ccEkle: "＋ Subtitle",
      ccDil: "Subtitle language",
      ccDosya: "Choose .vtt file",
      ccYukle: "Upload",
      ccBekle: "Uploading…",
      ccBasarili: "Subtitle added ✓",
      ccHata: (m) => `Couldn't add subtitle: ${m}`,
      bosMesaj: "Nothing here yet — send your first video from the Upload tab.",
      hata: (m) => `Couldn't load Studio: ${m}`,
      durum: {
        uploading: "Uploading",
        processing: "Processing",
        in_review: "In review",
        approved: "Live",
        rejected: "Rejected",
      },
    },
    panel: {
      kuyrukBaslik: "Review queue",
      kuyrukAciklama:
        "Approved videos go live immediately; a draft title is published along with them.",
      kuyrukBos: "Queue is clear — nothing to review.",
      onayla: "Approve & publish",
      reddet: "Reject",
      sponsorBaslik: "Sponsors",
      sponsorAciklama: "One active sponsor is shown as a 5-second card before every play.",
      sponsorAd: "Sponsor name",
      mesaj: "Message (optional)",
      ekle: "Add",
      aktif: "Active",
      pasif: "Paused",
      durdur: "Pause",
      surdur: "Resume",
      sil: "Delete",
      sponsorYok: "No sponsors yet.",
      yarismaBaslik: "Contests",
      yarismaAciklama: "The newest active contest is shown to everyone on the Contest tab.",
      yarismaAd: "Contest name",
      yarismaAciklamaAlan: "Description (optional)",
      baslat: "Launch",
      bitis: (tarih) => `ends: ${tarih}`,
      bitisYok: "no end date",
      acik: "Active",
      kapali: "Closed",
      kapat: "Close",
      yenidenAc: "Reopen",
      yarismaYok: "No contests yet.",
      denetim: "Audit log",
      sistem: "system",
      admin: "admin",
      aiRisk: {
        low: "AI: low risk",
        medium: "AI: medium risk",
        high: "AI: high risk",
      },
      eylem: {
        videos_approved: "Video approved",
        videos_rejected: "Video rejected",
        videos_in_review: "Video sent to review",
        titles_published: "Title published",
        titles_draft: "Title reverted to draft",
      },
    },
    analiz: {
      baslik: "Analytics",
      toplamIzlenme: "Total views",
      son7: "Last 7 days",
      tekilIzleyici: "Unique signed-in viewers",
      tekrarOrani: "Rewatch rate",
      gunluk: "Daily views (last 14 days)",
      enCok: "Most watched",
      veriYok: "No data.",
      izlenme: "views",
      yuzde: (n) => `${n}%`,
      hata: (m) => `Couldn't load analytics: ${m}`,
    },
    yarisma: {
      etiket: "CONTEST",
      yok: "No contest is running right now — the next one will show up here.",
      kalan: (n) => `${n} day${n === 1 ? "" : "s"} to go`,
      bitti: "This contest has ended — results below",
      sec: "Pick a title to enter…",
      katil: "Enter contest",
      girisYok: "No entries yet — creators with a published title can enter.",
      oy: (n) => `${n} vote${n === 1 ? "" : "s"}`,
      oyun: "Your vote ✓",
      oyVer: "Vote",
      katilimci: (n) => `${n} entr${n === 1 ? "y" : "ies"}`,
      toplamOy: (n) => `${n} votes total`,
      onde: "LEADING",
    },
  },

  tr: {
    locale: "tr-TR",
    belgeBasligi: "Latent — Yapay zekâ yapımı film ve diziler",
    nav: {
      kesfet: "Keşfet",
      yarisma: "Yarışma",
      yukle: "Yükle",
      studyo: "Stüdyo",
      panel: "Panel",
      analiz: "Analiz",
    },
    genel: {
      girisYap: "Giriş yap",
      cikis: "Çıkış",
      yukleniyor: "Yükleniyor…",
      geri: "← Geri",
      film: "Film",
      dizi: "Dizi",
      FILM: "FİLM",
      DIZI: "DİZİ",
      seb: (sezon, bolum) => `S${sezon}·B${bolum}`,
      bolumNo: (n) => `Bölüm ${n}`,
      dil: "Dil",
    },
    kabuk: {
      bildirimler: "Bildirimler",
      bildirimYok: "Henüz bildirim yok.",
      yayinda: "yayında",
      yeniIcerik: "Yeni içerik",
      dogrulanmadi: "E-posta adresin henüz doğrulanmadı — gelen kutunu kontrol et.",
      yenidenGonder: "Yeniden gönder",
      gonderildi: "Bağlantı gönderildi ✓",
      altBilgi1: "tüm içerikler tamamen yapay zekâ ile üretilmiştir.",
      altBilgi2: "İzlemek her zaman ücretsiz · Sanatçılar izlenmeyle kazanır",
    },
    hataEkrani: {
      baslik: "Bir şeyler ters gitti",
      govde: "Beklenmedik bir hata oluştu. Sayfayı yenilemek genellikle çözer.",
      yenile: "Sayfayı yenile",
    },
    ayarlar: {
      baslik: "Ayarlar",
      dilBolum: "Dil",
      altyaziBolum: "Alt yazı",
      altyaziAcik: "Alt yazıları otomatik göster",
      altyaziDil: "Alt yazı dili",
      arayuzDili: "Arayüz diliyle aynı",
      kapat: "Tamam",
      not: "Alt yazı, başlıkta o dilde bir alt yazı kaydı varsa görünür.",
    },
    kesfet: {
      ara: "Film ya da dizi ara…",
      sonuclar: "Arama sonuçları",
      sonucYok: "Sonuç bulunamadı.",
      tumu: "Tümü",
      filmler: "Filmler",
      diziler: "Diziler",
      baslikSayisi: (n) => `${n} başlık`,
      izle: "▶ İzle",
      filmiIzle: "▶ Filmi izle",
      devamEt: "İzlemeye devam et",
      kaldiginYerden: "kaldığın yerden",
      listem: "Listem",
      sanaOzel: "Sana özel",
      yeniEklenenler: "Yeni eklenenler",
      diger: "Diğer",
      listemde: "✓ Listemde",
      listemeEkle: "＋ Listeme ekle",
      paylas: "Paylaş",
      kopyalandi: "Bağlantı kopyalandı ✓",
      icerikYok: "Henüz yayınlanmış içerik yok.",
      sunucuYok: "Sunucuya ulaşılamadı — bağlantını kontrol edip sayfayı yenile.",
      katalogHata: (m) => `Katalog alınamadı: ${m}`,
      baslikHata: (m) => `Başlık alınamadı: ${m}`,
    },
    oynatici: {
      sponsorlu: "SPONSORLU",
      sponsoruZiyaret: "Sponsoru ziyaret et",
      baslayacak: (n) => `Video ${n} sn içinde başlayacak…`,
      sonrakiBolum: (n) => `Sonraki bölüm ${n} sn içinde`,
      simdiOynat: "▶ Şimdi oynat",
      kal: "Kal",
    },
    giris: {
      girisBaslik: "Giriş yap",
      kayitBaslik: "Hesap oluştur",
      girisAlt: "İzlemek her zaman ücretsiz. Giriş yüklemek ve listeler için.",
      kayitAlt: "Üretici olarak yüklemek için bir hesap yeterli.",
      ad: "Görünen ad",
      eposta: "E-posta",
      sifre: "Şifre",
      kayitAlindi: "Kayıt alındı. E-postanı doğruladıktan sonra giriş yapabilirsin.",
      bekle: "Bekle…",
      kayitOl: "Kayıt ol",
      hesapYok: "Hesabın yok mu?",
      hesapVar: "Zaten hesabın var mı?",
    },
    profil: {
      baslik: "Profil",
      gorunenAd: "Görünen ad",
      dogrulandi: "E-posta doğrulandı",
      dogrulanmadi: "E-posta doğrulanmadı",
      yenidenGonder: "Yeniden gönder",
      gonderildi: "Gönderildi ✓",
      kaydet: "Kaydet",
      vazgec: "Vazgeç",
    },
    yukle: {
      baslik: "Yükle",
      aciklama:
        "Video tarayıcından doğrudan Cloudflare'e gider; incelemeden geçtikten sonra yayınlanır.",
      baslikEtiket: "Başlık",
      yeniBaslik: "+ Yeni başlık oluştur",
      ad: "Ad",
      tip: "Tip",
      tur: "Tür (ör. Bilim Kurgu)",
      yil: "Yıl",
      aciklamaEtiket: "Açıklama",
      sezon: "Sezon",
      bolum: "Bölüm",
      bolumAdi: "Bölüm adı",
      dosya: "Video dosyası",
      yukleniyorYuzde: (n) => `Yükleniyor… %${n}`,
      baslat: "Yüklemeyi başlat",
      tamamBaslik: "Yükleme tamamlandı",
      tamamGovde:
        "Videon Cloudflare'de işleniyor. Hazır olunca incelemeye düşer; ekip onayladığında yayına çıkar.",
      yeniYukleme: "Yeni yükleme",
      hataBaslik: (m) => `Başlık oluşturulamadı: ${m}`,
      hataUrl: (m) => `Yükleme URL'i alınamadı: ${m}`,
      hataCf: (kod) => `Cloudflare yükleme hatası (${kod})`,
      hataAg: "Ağ hatası: yükleme tamamlanamadı",
    },
    studyo: {
      baslik: "Stüdyo",
      aciklama: "İçeriklerin, durumları ve izlenme özetin.",
      toplamIzlenme: "Toplam izlenme",
      izlenmeSaati: "Toplam izlenme saati",
      yayindaBolum: "Yayında bölüm",
      hakedis: "Hakediş",
      hakedisAciklama: "İzlenme başına gelir paylaşımına göre tahmini aylık döküm.",
      izlenme: "izlenme",
      ccEkle: "＋ Alt yazı",
      ccDil: "Alt yazı dili",
      ccDosya: ".vtt dosyası seç",
      ccYukle: "Yükle",
      ccBekle: "Yükleniyor…",
      ccBasarili: "Alt yazı eklendi ✓",
      ccHata: (m) => `Alt yazı eklenemedi: ${m}`,
      bosMesaj: "Henüz içeriğin yok — Yükle sekmesinden ilk videonu gönder.",
      hata: (m) => `Stüdyo verisi alınamadı: ${m}`,
      durum: {
        uploading: "Yükleniyor",
        processing: "İşleniyor",
        in_review: "İncelemede",
        approved: "Yayında",
        rejected: "Reddedildi",
      },
    },
    panel: {
      kuyrukBaslik: "İnceleme kuyruğu",
      kuyrukAciklama: "Onaylanan video anında yayına çıkar; başlığı taslaksa birlikte yayınlanır.",
      kuyrukBos: "Kuyruk boş — incelenecek video yok.",
      onayla: "Onayla ve yayınla",
      reddet: "Reddet",
      sponsorBaslik: "Sponsorlar",
      sponsorAciklama: "Aktif sponsorlardan biri her oynatma öncesi 5 sn'lik kart olarak gösterilir.",
      sponsorAd: "Sponsor adı",
      mesaj: "Mesaj (isteğe bağlı)",
      ekle: "Ekle",
      aktif: "Aktif",
      pasif: "Pasif",
      durdur: "Durdur",
      surdur: "Başlat",
      sil: "Sil",
      sponsorYok: "Henüz sponsor yok.",
      yarismaBaslik: "Yarışmalar",
      yarismaAciklama: "En yeni aktif yarışma, Yarışma sekmesinde herkese gösterilir.",
      yarismaAd: "Yarışma adı",
      yarismaAciklamaAlan: "Açıklama (isteğe bağlı)",
      baslat: "Başlat",
      bitis: (tarih) => `bitiş: ${tarih}`,
      bitisYok: "bitiş tarihi yok",
      acik: "Aktif",
      kapali: "Kapalı",
      kapat: "Kapat",
      yenidenAc: "Yeniden aç",
      yarismaYok: "Henüz yarışma yok.",
      denetim: "Denetim kaydı",
      sistem: "sistem",
      admin: "admin",
      aiRisk: {
        low: "YZ: düşük risk",
        medium: "YZ: orta risk",
        high: "YZ: yüksek risk",
      },
      eylem: {
        videos_approved: "Video onaylandı",
        videos_rejected: "Video reddedildi",
        videos_in_review: "Video incelemeye alındı",
        titles_published: "Başlık yayınlandı",
        titles_draft: "Başlık taslağa çekildi",
      },
    },
    analiz: {
      baslik: "Analiz",
      toplamIzlenme: "Toplam izlenme",
      son7: "Son 7 gün",
      tekilIzleyici: "Kayıtlı tekil izleyici",
      tekrarOrani: "Tekrar izleme oranı",
      gunluk: "Günlük izlenme (son 14 gün)",
      enCok: "En çok izlenenler",
      veriYok: "Veri yok.",
      izlenme: "izlenme",
      yuzde: (n) => `%${n}`,
      hata: (m) => `Analiz verisi alınamadı: ${m}`,
    },
    yarisma: {
      etiket: "YARIŞMA",
      yok: "Şu an aktif bir yarışma yok — yenisi duyurulduğunda burada olacak.",
      kalan: (n) => `Bitişe ${n} gün`,
      bitti: "Yarışma sona erdi — sonuçlar aşağıda",
      sec: "Yarışmaya katılacak başlığını seç…",
      katil: "Yarışmaya katıl",
      girisYok: "Henüz katılan içerik yok — yayınlanmış başlığı olan üreticiler katılabilir.",
      oy: (n) => `${n} oy`,
      oyun: "Oyun ✓",
      oyVer: "Oy ver",
      katilimci: (n) => `${n} katılımcı`,
      toplamOy: (n) => `toplam ${n} oy`,
      onde: "ÖNDE",
    },
  },

  es: {
    locale: "es-ES",
    belgeBasligi: "Latent — Cine y series hechos con IA",
    nav: {
      kesfet: "Descubrir",
      yarisma: "Concurso",
      yukle: "Subir",
      studyo: "Estudio",
      panel: "Revisión",
      analiz: "Analítica",
    },
    genel: {
      girisYap: "Iniciar sesión",
      cikis: "Cerrar sesión",
      yukleniyor: "Cargando…",
      geri: "← Volver",
      film: "Película",
      dizi: "Serie",
      FILM: "PELÍCULA",
      DIZI: "SERIE",
      seb: (sezon, bolum) => `T${sezon}·E${bolum}`,
      bolumNo: (n) => `Episodio ${n}`,
      dil: "Idioma",
    },
    kabuk: {
      bildirimler: "Notificaciones",
      bildirimYok: "Aún no hay notificaciones.",
      yayinda: "ya está disponible",
      yeniIcerik: "Nuevo título",
      dogrulanmadi: "Tu correo aún no está verificado — revisa tu bandeja de entrada.",
      yenidenGonder: "Reenviar",
      gonderildi: "Enlace enviado ✓",
      altBilgi1: "cada título está hecho completamente con IA.",
      altBilgi2: "Siempre gratis · Los artistas ganan por visualización",
    },
    hataEkrani: {
      baslik: "Algo salió mal",
      govde: "Ocurrió un error inesperado. Recargar la página suele solucionarlo.",
      yenile: "Recargar página",
    },
    ayarlar: {
      baslik: "Ajustes",
      dilBolum: "Idioma",
      altyaziBolum: "Subtítulos",
      altyaziAcik: "Mostrar subtítulos automáticamente",
      altyaziDil: "Idioma de los subtítulos",
      arayuzDili: "Igual que la interfaz",
      kapat: "Listo",
      not: "Los subtítulos aparecen si el título tiene una pista en ese idioma.",
    },
    kesfet: {
      ara: "Busca películas y series…",
      sonuclar: "Resultados de búsqueda",
      sonucYok: "No se encontraron resultados.",
      tumu: "Todo",
      filmler: "Películas",
      diziler: "Series",
      baslikSayisi: (n) => `${n} título${n === 1 ? "" : "s"}`,
      izle: "▶ Ver",
      filmiIzle: "▶ Ver la película",
      devamEt: "Seguir viendo",
      kaldiginYerden: "continúa donde lo dejaste",
      listem: "Mi lista",
      sanaOzel: "Para ti",
      yeniEklenenler: "Novedades",
      diger: "Otros",
      listemde: "✓ En mi lista",
      listemeEkle: "＋ Añadir a mi lista",
      paylas: "Compartir",
      kopyalandi: "Enlace copiado ✓",
      icerikYok: "Aún no hay nada publicado.",
      sunucuYok: "No se puede conectar con el servidor — revisa tu conexión y recarga.",
      katalogHata: (m) => `No se pudo cargar el catálogo: ${m}`,
      baslikHata: (m) => `No se pudo cargar el título: ${m}`,
    },
    oynatici: {
      sponsorlu: "PATROCINADO",
      sponsoruZiyaret: "Visitar patrocinador",
      baslayacak: (n) => `El vídeo empieza en ${n} s…`,
      sonrakiBolum: (n) => `Siguiente episodio en ${n} s`,
      simdiOynat: "▶ Reproducir ahora",
      kal: "Quedarme",
    },
    giris: {
      girisBaslik: "Iniciar sesión",
      kayitBaslik: "Crear cuenta",
      girisAlt: "Ver siempre es gratis. Inicia sesión para subir y guardar listas.",
      kayitAlt: "Una cuenta basta para subir como creador.",
      ad: "Nombre visible",
      eposta: "Correo",
      sifre: "Contraseña",
      kayitAlindi: "Listo. Verifica tu correo y luego inicia sesión.",
      bekle: "Un momento…",
      kayitOl: "Registrarse",
      hesapYok: "¿Aún no tienes cuenta?",
      hesapVar: "¿Ya tienes cuenta?",
    },
    profil: {
      baslik: "Perfil",
      gorunenAd: "Nombre visible",
      dogrulandi: "Correo verificado",
      dogrulanmadi: "Correo no verificado",
      yenidenGonder: "Reenviar",
      gonderildi: "Enviado ✓",
      kaydet: "Guardar",
      vazgec: "Cancelar",
    },
    yukle: {
      baslik: "Subir",
      aciklama:
        "Tu vídeo va directo del navegador a Cloudflare; se publica tras la revisión.",
      baslikEtiket: "Título",
      yeniBaslik: "+ Crear un título nuevo",
      ad: "Nombre",
      tip: "Tipo",
      tur: "Género (p. ej. ciencia ficción)",
      yil: "Año",
      aciklamaEtiket: "Descripción",
      sezon: "Temporada",
      bolum: "Episodio",
      bolumAdi: "Nombre del episodio",
      dosya: "Archivo de vídeo",
      yukleniyorYuzde: (n) => `Subiendo… ${n} %`,
      baslat: "Iniciar subida",
      tamamBaslik: "Subida completada",
      tamamGovde:
        "Tu vídeo se está procesando en Cloudflare. Cuando esté listo pasará a revisión; al aprobarse, se publicará.",
      yeniYukleme: "Subir otro",
      hataBaslik: (m) => `No se pudo crear el título: ${m}`,
      hataUrl: (m) => `No se pudo obtener la URL de subida: ${m}`,
      hataCf: (kod) => `Error de subida de Cloudflare (${kod})`,
      hataAg: "Error de red: la subida no terminó",
    },
    studyo: {
      baslik: "Estudio",
      aciklama: "Tus títulos, su estado y su rendimiento.",
      toplamIzlenme: "Visualizaciones totales",
      izlenmeSaati: "Horas vistas",
      yayindaBolum: "Episodios publicados",
      hakedis: "Ingresos",
      hakedisAciklama: "Desglose mensual estimado según el reparto por visualización.",
      izlenme: "visualizaciones",
      ccEkle: "＋ Subtítulo",
      ccDil: "Idioma del subtítulo",
      ccDosya: "Elegir archivo .vtt",
      ccYukle: "Subir",
      ccBekle: "Subiendo…",
      ccBasarili: "Subtítulo añadido ✓",
      ccHata: (m) => `No se pudo añadir el subtítulo: ${m}`,
      bosMesaj: "Aún no tienes contenido — envía tu primer vídeo desde Subir.",
      hata: (m) => `No se pudo cargar Estudio: ${m}`,
      durum: {
        uploading: "Subiendo",
        processing: "Procesando",
        in_review: "En revisión",
        approved: "Publicado",
        rejected: "Rechazado",
      },
    },
    panel: {
      kuyrukBaslik: "Cola de revisión",
      kuyrukAciklama:
        "Los vídeos aprobados se publican al instante; si el título es borrador, se publica con ellos.",
      kuyrukBos: "Cola vacía — nada que revisar.",
      onayla: "Aprobar y publicar",
      reddet: "Rechazar",
      sponsorBaslik: "Patrocinadores",
      sponsorAciklama:
        "Uno de los patrocinadores activos se muestra 5 s antes de cada reproducción.",
      sponsorAd: "Nombre del patrocinador",
      mesaj: "Mensaje (opcional)",
      ekle: "Añadir",
      aktif: "Activo",
      pasif: "Pausado",
      durdur: "Pausar",
      surdur: "Reanudar",
      sil: "Eliminar",
      sponsorYok: "Aún no hay patrocinadores.",
      yarismaBaslik: "Concursos",
      yarismaAciklama:
        "El concurso activo más reciente se muestra a todos en la pestaña Concurso.",
      yarismaAd: "Nombre del concurso",
      yarismaAciklamaAlan: "Descripción (opcional)",
      baslat: "Lanzar",
      bitis: (tarih) => `termina: ${tarih}`,
      bitisYok: "sin fecha de fin",
      acik: "Activo",
      kapali: "Cerrado",
      kapat: "Cerrar",
      yenidenAc: "Reabrir",
      yarismaYok: "Aún no hay concursos.",
      denetim: "Registro de auditoría",
      sistem: "sistema",
      admin: "admin",
      eylem: {
        videos_approved: "Vídeo aprobado",
        videos_rejected: "Vídeo rechazado",
        videos_in_review: "Vídeo enviado a revisión",
        titles_published: "Título publicado",
        titles_draft: "Título devuelto a borrador",
      },
      aiRisk: {
        low: "IA: riesgo bajo",
        medium: "IA: riesgo medio",
        high: "IA: riesgo alto",
      },
    },
    analiz: {
      baslik: "Analítica",
      toplamIzlenme: "Visualizaciones totales",
      son7: "Últimos 7 días",
      tekilIzleyici: "Espectadores únicos registrados",
      tekrarOrani: "Tasa de revisionado",
      gunluk: "Visualizaciones diarias (últimos 14 días)",
      enCok: "Lo más visto",
      veriYok: "Sin datos.",
      izlenme: "visualizaciones",
      yuzde: (n) => `${n} %`,
      hata: (m) => `No se pudo cargar la analítica: ${m}`,
    },
    yarisma: {
      etiket: "CONCURSO",
      yok: "Ahora mismo no hay ningún concurso — el próximo aparecerá aquí.",
      kalan: (n) => `Quedan ${n} día${n === 1 ? "" : "s"}`,
      bitti: "Este concurso ha terminado — resultados abajo",
      sec: "Elige un título para participar…",
      katil: "Participar",
      girisYok:
        "Aún no hay participantes — pueden participar los creadores con un título publicado.",
      oy: (n) => `${n} voto${n === 1 ? "" : "s"}`,
      oyun: "Tu voto ✓",
      oyVer: "Votar",
      katilimci: (n) => `${n} participante${n === 1 ? "" : "s"}`,
      toplamOy: (n) => `${n} votos en total`,
      onde: "LÍDER",
    },
  },

  de: {
    locale: "de-DE",
    belgeBasligi: "Latent — KI-Filme & -Serien",
    nav: {
      kesfet: "Entdecken",
      yarisma: "Wettbewerb",
      yukle: "Hochladen",
      studyo: "Studio",
      panel: "Prüfung",
      analiz: "Analysen",
    },
    genel: {
      girisYap: "Anmelden",
      cikis: "Abmelden",
      yukleniyor: "Lädt…",
      geri: "← Zurück",
      film: "Film",
      dizi: "Serie",
      FILM: "FILM",
      DIZI: "SERIE",
      seb: (sezon, bolum) => `S${sezon}·E${bolum}`,
      bolumNo: (n) => `Folge ${n}`,
      dil: "Sprache",
    },
    kabuk: {
      bildirimler: "Benachrichtigungen",
      bildirimYok: "Noch keine Benachrichtigungen.",
      yayinda: "ist online",
      yeniIcerik: "Neuer Titel",
      dogrulanmadi:
        "Deine E-Mail ist noch nicht bestätigt — sieh in deinem Posteingang nach.",
      yenidenGonder: "Erneut senden",
      gonderildi: "Link gesendet ✓",
      altBilgi1: "jeder Titel ist vollständig KI-generiert.",
      altBilgi2: "Immer kostenlos · Kunstschaffende verdienen pro Aufruf",
    },
    hataEkrani: {
      baslik: "Etwas ist schiefgelaufen",
      govde: "Ein unerwarteter Fehler ist aufgetreten. Ein Neuladen behebt das meist.",
      yenile: "Seite neu laden",
    },
    ayarlar: {
      baslik: "Einstellungen",
      dilBolum: "Sprache",
      altyaziBolum: "Untertitel",
      altyaziAcik: "Untertitel automatisch anzeigen",
      altyaziDil: "Untertitelsprache",
      arayuzDili: "Wie die Oberfläche",
      kapat: "Fertig",
      not: "Untertitel erscheinen, wenn der Titel eine Spur in dieser Sprache hat.",
    },
    kesfet: {
      ara: "Filme und Serien suchen…",
      sonuclar: "Suchergebnisse",
      sonucYok: "Keine Ergebnisse gefunden.",
      tumu: "Alle",
      filmler: "Filme",
      diziler: "Serien",
      baslikSayisi: (n) => `${n} Titel`,
      izle: "▶ Ansehen",
      filmiIzle: "▶ Film ansehen",
      devamEt: "Weiterschauen",
      kaldiginYerden: "mach da weiter, wo du warst",
      listem: "Meine Liste",
      sanaOzel: "Für dich",
      yeniEklenenler: "Neuheiten",
      diger: "Sonstiges",
      listemde: "✓ In meiner Liste",
      listemeEkle: "＋ Zu meiner Liste",
      paylas: "Teilen",
      kopyalandi: "Link kopiert ✓",
      icerikYok: "Noch nichts veröffentlicht.",
      sunucuYok: "Server nicht erreichbar — prüfe deine Verbindung und lade neu.",
      katalogHata: (m) => `Katalog konnte nicht geladen werden: ${m}`,
      baslikHata: (m) => `Titel konnte nicht geladen werden: ${m}`,
    },
    oynatici: {
      sponsorlu: "GESPONSERT",
      sponsoruZiyaret: "Sponsor besuchen",
      baslayacak: (n) => `Video startet in ${n} s…`,
      sonrakiBolum: (n) => `Nächste Folge in ${n} s`,
      simdiOynat: "▶ Jetzt abspielen",
      kal: "Bleiben",
    },
    giris: {
      girisBaslik: "Anmelden",
      kayitBaslik: "Konto erstellen",
      girisAlt:
        "Zuschauen ist immer kostenlos. Melde dich an, um hochzuladen und Listen zu führen.",
      kayitAlt: "Ein Konto genügt, um als Creator hochzuladen.",
      ad: "Anzeigename",
      eposta: "E-Mail",
      sifre: "Passwort",
      kayitAlindi: "Geschafft. Bestätige deine E-Mail und melde dich dann an.",
      bekle: "Einen Moment…",
      kayitOl: "Registrieren",
      hesapYok: "Noch kein Konto?",
      hesapVar: "Schon ein Konto?",
    },
    profil: {
      baslik: "Profil",
      gorunenAd: "Anzeigename",
      dogrulandi: "E-Mail bestätigt",
      dogrulanmadi: "E-Mail nicht bestätigt",
      yenidenGonder: "Erneut senden",
      gonderildi: "Gesendet ✓",
      kaydet: "Speichern",
      vazgec: "Abbrechen",
    },
    yukle: {
      baslik: "Hochladen",
      aciklama:
        "Dein Video geht direkt vom Browser zu Cloudflare; nach der Prüfung wird es veröffentlicht.",
      baslikEtiket: "Titel",
      yeniBaslik: "+ Neuen Titel anlegen",
      ad: "Name",
      tip: "Typ",
      tur: "Genre (z. B. Science-Fiction)",
      yil: "Jahr",
      aciklamaEtiket: "Beschreibung",
      sezon: "Staffel",
      bolum: "Folge",
      bolumAdi: "Folgenname",
      dosya: "Videodatei",
      yukleniyorYuzde: (n) => `Wird hochgeladen… ${n} %`,
      baslat: "Upload starten",
      tamamBaslik: "Upload abgeschlossen",
      tamamGovde:
        "Dein Video wird bei Cloudflare verarbeitet. Sobald es fertig ist, geht es in die Prüfung; nach Freigabe wird es veröffentlicht.",
      yeniYukleme: "Weiteres hochladen",
      hataBaslik: (m) => `Titel konnte nicht angelegt werden: ${m}`,
      hataUrl: (m) => `Upload-URL konnte nicht geholt werden: ${m}`,
      hataCf: (kod) => `Cloudflare-Upload-Fehler (${kod})`,
      hataAg: "Netzwerkfehler: Der Upload wurde nicht abgeschlossen",
    },
    studyo: {
      baslik: "Studio",
      aciklama: "Deine Titel, ihr Status und ihre Performance.",
      toplamIzlenme: "Aufrufe gesamt",
      izlenmeSaati: "Wiedergabestunden",
      yayindaBolum: "Folgen online",
      hakedis: "Einnahmen",
      hakedisAciklama:
        "Geschätzte monatliche Aufstellung nach Umsatzbeteiligung pro Aufruf.",
      izlenme: "Aufrufe",
      ccEkle: "＋ Untertitel",
      ccDil: "Untertitelsprache",
      ccDosya: ".vtt-Datei wählen",
      ccYukle: "Hochladen",
      ccBekle: "Wird hochgeladen…",
      ccBasarili: "Untertitel hinzugefügt ✓",
      ccHata: (m) => `Untertitel konnte nicht hinzugefügt werden: ${m}`,
      bosMesaj: "Noch nichts hier — schick dein erstes Video über Hochladen.",
      hata: (m) => `Studio konnte nicht geladen werden: ${m}`,
      durum: {
        uploading: "Wird hochgeladen",
        processing: "In Verarbeitung",
        in_review: "In Prüfung",
        approved: "Online",
        rejected: "Abgelehnt",
      },
    },
    panel: {
      kuyrukBaslik: "Prüfwarteschlange",
      kuyrukAciklama:
        "Freigegebene Videos gehen sofort online; ein Titel im Entwurf wird mit veröffentlicht.",
      kuyrukBos: "Warteschlange leer — nichts zu prüfen.",
      onayla: "Freigeben & veröffentlichen",
      reddet: "Ablehnen",
      sponsorBaslik: "Sponsoren",
      sponsorAciklama:
        "Einer der aktiven Sponsoren wird vor jeder Wiedergabe 5 s eingeblendet.",
      sponsorAd: "Sponsorname",
      mesaj: "Nachricht (optional)",
      ekle: "Hinzufügen",
      aktif: "Aktiv",
      pasif: "Pausiert",
      durdur: "Pausieren",
      surdur: "Fortsetzen",
      sil: "Löschen",
      sponsorYok: "Noch keine Sponsoren.",
      yarismaBaslik: "Wettbewerbe",
      yarismaAciklama:
        "Der neueste aktive Wettbewerb wird allen im Wettbewerb-Tab angezeigt.",
      yarismaAd: "Wettbewerbsname",
      yarismaAciklamaAlan: "Beschreibung (optional)",
      baslat: "Starten",
      bitis: (tarih) => `endet: ${tarih}`,
      bitisYok: "kein Enddatum",
      acik: "Aktiv",
      kapali: "Geschlossen",
      kapat: "Schließen",
      yenidenAc: "Wieder öffnen",
      yarismaYok: "Noch keine Wettbewerbe.",
      denetim: "Audit-Log",
      sistem: "System",
      admin: "Admin",
      eylem: {
        videos_approved: "Video freigegeben",
        videos_rejected: "Video abgelehnt",
        videos_in_review: "Video in Prüfung geschickt",
        titles_published: "Titel veröffentlicht",
        titles_draft: "Titel in Entwurf zurückgesetzt",
      },
      aiRisk: {
        low: "KI: geringes Risiko",
        medium: "KI: mittleres Risiko",
        high: "KI: hohes Risiko",
      },
    },
    analiz: {
      baslik: "Analysen",
      toplamIzlenme: "Aufrufe gesamt",
      son7: "Letzte 7 Tage",
      tekilIzleyici: "Angemeldete Einzelzuschauer",
      tekrarOrani: "Wiederholungsquote",
      gunluk: "Tägliche Aufrufe (letzte 14 Tage)",
      enCok: "Meistgesehen",
      veriYok: "Keine Daten.",
      izlenme: "Aufrufe",
      yuzde: (n) => `${n} %`,
      hata: (m) => `Analysen konnten nicht geladen werden: ${m}`,
    },
    yarisma: {
      etiket: "WETTBEWERB",
      yok: "Zurzeit läuft kein Wettbewerb — der nächste erscheint hier.",
      kalan: (n) => `Noch ${n} Tag${n === 1 ? "" : "e"}`,
      bitti: "Dieser Wettbewerb ist beendet — Ergebnisse unten",
      sec: "Wähle einen Titel zur Teilnahme…",
      katil: "Teilnehmen",
      girisYok:
        "Noch keine Teilnehmer — Creator mit veröffentlichtem Titel können teilnehmen.",
      oy: (n) => `${n} Stimme${n === 1 ? "" : "n"}`,
      oyun: "Deine Stimme ✓",
      oyVer: "Abstimmen",
      katilimci: (n) => `${n} Teilnehmer`,
      toplamOy: (n) => `${n} Stimmen insgesamt`,
      onde: "FÜHRT",
    },
  },

  fr: {
    locale: "fr-FR",
    belgeBasligi: "Latent — Films et séries créés par IA",
    nav: {
      kesfet: "Découvrir",
      yarisma: "Concours",
      yukle: "Publier",
      studyo: "Studio",
      panel: "Révision",
      analiz: "Analyses",
    },
    genel: {
      girisYap: "Se connecter",
      cikis: "Se déconnecter",
      yukleniyor: "Chargement…",
      geri: "← Retour",
      film: "Film",
      dizi: "Série",
      FILM: "FILM",
      DIZI: "SÉRIE",
      seb: (sezon, bolum) => `S${sezon}·E${bolum}`,
      bolumNo: (n) => `Épisode ${n}`,
      dil: "Langue",
    },
    kabuk: {
      bildirimler: "Notifications",
      bildirimYok: "Pas encore de notifications.",
      yayinda: "est en ligne",
      yeniIcerik: "Nouveau titre",
      dogrulanmadi:
        "Ton e-mail n'est pas encore vérifié — regarde ta boîte de réception.",
      yenidenGonder: "Renvoyer",
      gonderildi: "Lien envoyé ✓",
      altBilgi1: "chaque titre est entièrement créé par IA.",
      altBilgi2: "Toujours gratuit · Les artistes gagnent à la vue",
    },
    hataEkrani: {
      baslik: "Un problème est survenu",
      govde: "Une erreur inattendue s'est produite. Recharger la page suffit souvent.",
      yenile: "Recharger la page",
    },
    ayarlar: {
      baslik: "Paramètres",
      dilBolum: "Langue",
      altyaziBolum: "Sous-titres",
      altyaziAcik: "Afficher les sous-titres automatiquement",
      altyaziDil: "Langue des sous-titres",
      arayuzDili: "Comme l'interface",
      kapat: "Terminé",
      not: "Les sous-titres s'affichent si le titre a une piste dans cette langue.",
    },
    kesfet: {
      ara: "Rechercher films et séries…",
      sonuclar: "Résultats de recherche",
      sonucYok: "Aucun résultat trouvé.",
      tumu: "Tout",
      filmler: "Films",
      diziler: "Séries",
      baslikSayisi: (n) => `${n} titre${n === 1 ? "" : "s"}`,
      izle: "▶ Regarder",
      filmiIzle: "▶ Regarder le film",
      devamEt: "Reprendre la lecture",
      kaldiginYerden: "reprends là où tu t'étais arrêté",
      listem: "Ma liste",
      sanaOzel: "Pour toi",
      yeniEklenenler: "Nouveautés",
      diger: "Autres",
      listemde: "✓ Dans ma liste",
      listemeEkle: "＋ Ajouter à ma liste",
      paylas: "Partager",
      kopyalandi: "Lien copié ✓",
      icerikYok: "Rien n'est encore publié.",
      sunucuYok: "Serveur injoignable — vérifie ta connexion et recharge.",
      katalogHata: (m) => `Impossible de charger le catalogue : ${m}`,
      baslikHata: (m) => `Impossible de charger le titre : ${m}`,
    },
    oynatici: {
      sponsorlu: "SPONSORISÉ",
      sponsoruZiyaret: "Visiter le sponsor",
      baslayacak: (n) => `La vidéo démarre dans ${n} s…`,
      sonrakiBolum: (n) => `Épisode suivant dans ${n} s`,
      simdiOynat: "▶ Lire maintenant",
      kal: "Rester",
    },
    giris: {
      girisBaslik: "Se connecter",
      kayitBaslik: "Créer un compte",
      girisAlt:
        "Regarder est toujours gratuit. Connecte-toi pour publier et gérer tes listes.",
      kayitAlt: "Un compte suffit pour publier en tant que créateur.",
      ad: "Nom affiché",
      eposta: "E-mail",
      sifre: "Mot de passe",
      kayitAlindi: "C'est fait. Vérifie ton e-mail puis connecte-toi.",
      bekle: "Un instant…",
      kayitOl: "S'inscrire",
      hesapYok: "Pas encore de compte ?",
      hesapVar: "Déjà un compte ?",
    },
    profil: {
      baslik: "Profil",
      gorunenAd: "Nom affiché",
      dogrulandi: "E-mail vérifié",
      dogrulanmadi: "E-mail non vérifié",
      yenidenGonder: "Renvoyer",
      gonderildi: "Envoyé ✓",
      kaydet: "Enregistrer",
      vazgec: "Annuler",
    },
    yukle: {
      baslik: "Publier",
      aciklama:
        "Ta vidéo va directement du navigateur à Cloudflare ; elle est publiée après révision.",
      baslikEtiket: "Titre",
      yeniBaslik: "+ Créer un nouveau titre",
      ad: "Nom",
      tip: "Type",
      tur: "Genre (p. ex. science-fiction)",
      yil: "Année",
      aciklamaEtiket: "Description",
      sezon: "Saison",
      bolum: "Épisode",
      bolumAdi: "Nom de l'épisode",
      dosya: "Fichier vidéo",
      yukleniyorYuzde: (n) => `Envoi… ${n} %`,
      baslat: "Lancer l'envoi",
      tamamBaslik: "Envoi terminé",
      tamamGovde:
        "Ta vidéo est en cours de traitement chez Cloudflare. Une fois prête, elle passe en révision ; après approbation, elle est publiée.",
      yeniYukleme: "En publier une autre",
      hataBaslik: (m) => `Impossible de créer le titre : ${m}`,
      hataUrl: (m) => `Impossible d'obtenir l'URL d'envoi : ${m}`,
      hataCf: (kod) => `Erreur d'envoi Cloudflare (${kod})`,
      hataAg: "Erreur réseau : l'envoi ne s'est pas terminé",
    },
    studyo: {
      baslik: "Studio",
      aciklama: "Tes titres, leur statut et leurs performances.",
      toplamIzlenme: "Vues totales",
      izlenmeSaati: "Heures de visionnage",
      yayindaBolum: "Épisodes en ligne",
      hakedis: "Revenus",
      hakedisAciklama: "Estimation mensuelle selon le partage des revenus par vue.",
      izlenme: "vues",
      ccEkle: "＋ Sous-titres",
      ccDil: "Langue des sous-titres",
      ccDosya: "Choisir un fichier .vtt",
      ccYukle: "Envoyer",
      ccBekle: "Envoi…",
      ccBasarili: "Sous-titres ajoutés ✓",
      ccHata: (m) => `Impossible d'ajouter les sous-titres : ${m}`,
      bosMesaj: "Rien ici pour l'instant — envoie ta première vidéo depuis Publier.",
      hata: (m) => `Impossible de charger le Studio : ${m}`,
      durum: {
        uploading: "Envoi en cours",
        processing: "En traitement",
        in_review: "En révision",
        approved: "En ligne",
        rejected: "Refusé",
      },
    },
    panel: {
      kuyrukBaslik: "File de révision",
      kuyrukAciklama:
        "Les vidéos approuvées sont publiées immédiatement ; un titre en brouillon est publié avec.",
      kuyrukBos: "File vide — rien à réviser.",
      onayla: "Approuver et publier",
      reddet: "Refuser",
      sponsorBaslik: "Sponsors",
      sponsorAciklama:
        "Un des sponsors actifs s'affiche 5 s avant chaque lecture.",
      sponsorAd: "Nom du sponsor",
      mesaj: "Message (facultatif)",
      ekle: "Ajouter",
      aktif: "Actif",
      pasif: "En pause",
      durdur: "Suspendre",
      surdur: "Reprendre",
      sil: "Supprimer",
      sponsorYok: "Pas encore de sponsors.",
      yarismaBaslik: "Concours",
      yarismaAciklama:
        "Le concours actif le plus récent est visible par tous dans l'onglet Concours.",
      yarismaAd: "Nom du concours",
      yarismaAciklamaAlan: "Description (facultative)",
      baslat: "Lancer",
      bitis: (tarih) => `fin : ${tarih}`,
      bitisYok: "pas de date de fin",
      acik: "Actif",
      kapali: "Fermé",
      kapat: "Fermer",
      yenidenAc: "Rouvrir",
      yarismaYok: "Pas encore de concours.",
      denetim: "Journal d'audit",
      sistem: "système",
      admin: "admin",
      eylem: {
        videos_approved: "Vidéo approuvée",
        videos_rejected: "Vidéo refusée",
        videos_in_review: "Vidéo envoyée en révision",
        titles_published: "Titre publié",
        titles_draft: "Titre repassé en brouillon",
      },
      aiRisk: {
        low: "IA : risque faible",
        medium: "IA : risque moyen",
        high: "IA : risque élevé",
      },
    },
    analiz: {
      baslik: "Analyses",
      toplamIzlenme: "Vues totales",
      son7: "7 derniers jours",
      tekilIzleyici: "Spectateurs connectés uniques",
      tekrarOrani: "Taux de revisionnage",
      gunluk: "Vues quotidiennes (14 derniers jours)",
      enCok: "Les plus regardés",
      veriYok: "Pas de données.",
      izlenme: "vues",
      yuzde: (n) => `${n} %`,
      hata: (m) => `Impossible de charger les analyses : ${m}`,
    },
    yarisma: {
      etiket: "CONCOURS",
      yok: "Aucun concours en cours — le prochain apparaîtra ici.",
      kalan: (n) => `${n} jour${n === 1 ? "" : "s"} restant${n === 1 ? "" : "s"}`,
      bitti: "Ce concours est terminé — résultats ci-dessous",
      sec: "Choisis un titre pour participer…",
      katil: "Participer",
      girisYok:
        "Pas encore de participants — les créateurs avec un titre publié peuvent participer.",
      oy: (n) => `${n} vote${n === 1 ? "" : "s"}`,
      oyun: "Ton vote ✓",
      oyVer: "Voter",
      katilimci: (n) => `${n} participant${n === 1 ? "" : "s"}`,
      toplamOy: (n) => `${n} votes au total`,
      onde: "EN TÊTE",
    },
  },
};
